#!/usr/bin/env bash
#
# Shell script which typesets shinn_resume.tex and copy the result to the
# local directory of abshinn.github.io (blog).

echo "Typesetting shinn_resume.tex..."
sleep 1;

pdflatex shinn_resume.tex ;

echo
echo "Copy to abshinn.github.io local directory..."
sleep 1;

cp shinn_resume.pdf ~/abshinn.github.io/shinn_resume.pdf
cp shinn_resume.pdf ~/abshinn.github.io/resume.pdf
